### ISSUE TITLE
Add a ThankCommand or way to track thanks within the server

### ISSUE THREAD

**Issue by devldm** [Tobio89/fcc-bot-go#32]
## The issue
Currently there is no way to thank other users in the server outside of a basic message or emoji. We also currently don't keep track of `thanks` so it's hard to see who contributes most to users in need. 

### Thanks Command - Code complete 
I believe one solution to this could be the addition of a `ThankCommand`. This would allow others to call out users and share the appreciation as a new `thanks message` is created by the bot which could be sent to any channel. (a specific `thanks` channel in my changes) .

**The changes to add this command can be seen [here](https://github.com/devldm/fcc-bot-go/pull/1)**. If the changes seem like a good suggestion i can re-create the PR merging into this repository where we can discuss changes etc so we don't lose git history / context. 

### Emoji tracking - WIP
This would need further work but the initial changes can be seen in a WIP pr [here](https://github.com/devldm/fcc-bot-go/pull/2). We add a check for a newly added `thanks emoji` where we could trigger methods to track or handle the data.  

I think the addition of a `thank` specific emoji as seen [here](https://emoji.gg/emoji/2016-blobthanks) could be a good move regardless of the above changes progress.

## Next steps
I am happy to do some further work on `Emoji Tracking` or raise a new PR for a `thanks command` as a follow up to your thoughts but i wanted to raise my suggestions here as a issue first. 

If neither of these seem like a good move for the bot feel free to close the issue or offer alternative paths if you have something in mind but don't quite have the time to implement! Thanks.

**Comment by Tobio89** [comment]
That's a good suggestion, and I did want to implement something a bit like that in the future.
My vision was to use an emoji such as 👍🏻  or 🙏🏻, and use this, along with a database, to be able to track a user's 'helpfulness'.

Then later, change the role scheme so that a role level is given for power users

Thanks!
I think the first step is to add a database 🤔 
Well, the zeroth step is to fix the delete command haha
